terraform-ibm-modules/terraform-ibm-satellite

modules/cluster_host/scripts/assign_cluster_host.sh
The command fails since the hostname doesn't exist within the location yet.
=> Wait for host to exist

examples/satellite-azure/variables.tf
add TF_VERSION to azure variables.tf and default it to 0.13, for use with schematics.
=> Add TF_VERSION to azure variables.tf

.github/workflows/validate_terraform.yml, examples/satellite-aws/README.md, examples/satellite-aws/variables.tf
- Don't restrict aws instance types.
- Update readme to correct default.
=> remove instance type restrictions for AWS

examples/satellite-aws/README.md, examples/satellite-azure/README.md, examples/satellite-azure/host.tf, examples/satellite-azure/instance.tf, examples/satellite-azure/locals.tf, examples/satellite-azure/outputs.tf, examples/satellite-azure/variables.tf
Add variables options for specifying multiple types of hosts. Similar to the AWS one, tested with supplying both the following
```
cp_hosts = [
{
count         = 3
instance_type = "Standard_D4as_v4"
},
{
count         = 6
instance_type = "Standard_D4s_v4"
}
]
addl_hosts = [
{
count         = 3
instance_type = "Standard_D4as_v4"
}
]
```
After speaking with @jsloyer we should be enforcing multiples of 3 service hosts, not just control plane.
=> Azure multi-host support

examples/satellite-azure/variables.tf, examples/satellite-gcp/variables.tf
Don't allow capital letters or periods in prefix for azure
Azure doesn't like capitals, and at host assign, the passed host ID does a split on ".". For GCP and Azure resource prefix gets used for host ID, as a result a split occurs on the prefix ex.
```
prefix = "satellite.azure"
host ID = split(".", ["satellite.azure-vm-1", "satellite.azure-vm-2", "satellite.azure-vm-3"]) // result is [satellite, satellite, satellite]
=> Add regex for prefix

examples/satellite-azure/variables.tf, examples/satellite-gcp/README.md, examples/satellite-gcp/host.tf, examples/satellite-gcp/instance.tf, examples/satellite-gcp/locals.tf, examples/satellite-gcp/outputs.tf, examples/satellite-gcp/variables.tf
Add variables options for specifying multiple types of hosts. Similar to the AWS and azure one, tested with supplying both the following
```
cp_hosts = [
{
count         = 3
instance_type = "n2-standard-4"
},
{
count         = 6
instance_type = "n2-standard-8"
}
]
addl_hosts = [
{
count         = 3
instance_type = "n2-standard-4"
}
]
```
=> Support creating multiple host types with a single terraform for GCP

examples/satellite-aws/versions.tf, examples/satellite-azure/versions.tf, examples/satellite-gcp/versions.tf, examples/satellite-ibm/versions.tf
Right now we have no versioning on IBM which caused the provider to bump to a place that would break reading existing satellite locations. Revert the provider version and code in a version # to prevent that.
```
2022/08/02 14:22:59 Terraform plan | Error: Plugin did not respond
2022/08/02 14:22:59 Terraform plan | 
2022/08/02 14:22:59 Terraform plan |   with module.satellite-location.data.ibm_satellite_location.location,
2022/08/02 14:22:59 Terraform plan |   on modules/location/main.tf line 19, in data "ibm_satellite_location" "location":
2022/08/02 14:22:59 Terraform plan |   19: data "ibm_satellite_location" "location" {
2022/08/02 14:22:59 Terraform plan | 
2022/08/02 14:22:59 Terraform plan | The plugin encountered an error, and failed to respond to the
2022/08/02 14:22:59 Terraform …
```
=> Add versioning to ibm, tls, and each provider

examples/satellite-azure/README.md, examples/satellite-azure/instance.tf, examples/satellite-azure/variables.tf, examples/satellite-gcp/README.md, examples/satellite-gcp/instance.tf, examples/satellite-gcp/variables.tf, examples/satellite-ibm/README.md, examples/satellite-ibm/instance.tf, examples/satellite-ibm/variables.tf
We're going to start allowing people to choose between rhel 7 and 8 when creating hosts because rhel 7 is being deprecated within the next half year.
=> Add image selection for all providers

examples/satellite-azure/variables.tf
- when passing in kube_version, don't pass in the patch level. That is automatically chosen for you. As it was, the patch level specified was old, so deploy would fail.
- set `create_cluster` default to `false`. This is what we wanted but it got lost in the shuffle of the previous PR.
=> azure - ocp version, default create_cluster false

.pre-commit-config.yaml, .secrets.baseline, examples/satellite-aws/variables.tf
Previous image is deprecated. Amazon removes images after 2 years, so bump it up to one that expires in 2024
=> Bump aws ami default

examples/satellite-aws/instance.tf
Because `aws_placement_group.satellite_group` is a resource, its id value is recalculated each time causing all hosts to be destroyed and remade. Instead use the pg name which we know as it is equal to the id. The default `spread_level` is also "rack" so put that in so it doesn't recalculate from null -> rack -> null and cause issues as well.
https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/ec2/ec2_placement_group.go#L103 for evidence of id being set equal to name. 
Throw the resource as a dependency also into the instance. I tested with changing zones which blocked me (good) as that would have changed the PG, and I also changed the resource prefix which caused everything to be destroyed/remade (also good).
=> Dont recalculate pg name every time

.pre-commit-config.yaml, .secrets.baseline, examples/satellite-aws/instance.tf
Right now the user data passed in is around 12KB, max for AWS is 16KB. Switch it over to base64 to prevent issues.
Azure, GCP, and IBM are all covered/have capable room to grow.
=> Encode aws user data to base64

.pre-commit-config.yaml, .secrets.baseline, examples/satellite-aws/versions.tf, examples/satellite-azure/versions.tf, examples/satellite-gcp/versions.tf, examples/satellite-ibm/versions.tf
Provider version has bumped and supports rhel8 without unnecessary hacks for python versioning.
=> Bump provider version to support rhel8

examples/satellite-aws/instance.tf
Update AWS template to use `gp3` ebs volumes for the `root_block_device` of the created ec2 instances. 
gp3 is better and cheaper than gp2:
https://aws.amazon.com/ebs/general-purpose/
Signed-off-by: Edward Fink <finken@us.ibm.com>
=> use gp3 root block device on AWS ec2

examples/satellite-vmware/README.md, examples/satellite-vmware/main.tf, examples/satellite-vmware/variables.tf, examples/satellite-vmware/versions.tf
Updates to the VMware example only:
- Specify a required version for the ibm terraform provider.
- Make gateway optional. If it's not provided, user will need to manually configure firewall and NAT. This will allow for more flexibility since networking environments vary quite a bit.
- Update README
- Update some descriptions in `variables.tf`
- Remove some defaults in `variables.tf`. Those values are required, so they shouldn't be defaulted to empty strings.
=> VMware example: Make gateway optional, update README

examples/satellite-vmware/versions.tf
[previous PR](https://github.com/terraform-ibm-modules/terraform-ibm-satellite/pull/89) didn't bump this example, but some of our ci [_sometimes_](https://github.com/terraform-ibm-modules/terraform-ibm-satellite/actions/runs/9290163732) got upset.
=> fix(vmware example): bump provider version 1.64.0

examples/satellite-aws/variables.tf
bump the default aws_ami.  The old one was deprecated and deleted.
=> fix(aws example): bump aws_ami to RHEL 8.9

examples/satellite-azure/cluster.tf, examples/satellite-vmware/main.tf
Because we package up the examples, we need to make sure they're pointing to the module code that they're built with. Most of them are, but a few of these were still pointing to the registry.
=> fix(examples): don't point to registry for modules

make-release-satellite.sh
We previously weren't using any of the modules for the vmware example, so weren't including. Need to include them in the tgz so we're locked on the built version.
=> fix(vmware): include modules in tgz

examples/satellite-ibm/README.md, examples/satellite-ibm/locals.tf, examples/satellite-ibm/variables.tf
Add an ssh security group option to the ibm cloud example. 
No change to the default behavior, but we can send false so that the SG isn't open to external SSH.
=> feat: add ssh security group option to IBM example
